layout: stacked
style: light

encoding: utf-8

repository: s0ph1e/personal-website
url: https://sophia.antipenko.pp.ua

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 300
  exclude:
    archived: false
    forks: false
    # projects:
  include:
    - node-website-scraper
    - website-scraper-puppeteer
    - node-website-scraper-phantom
    - demo
    - star-history
    - travel-from-ukraine
    - eml-reader
    - uz-search
    - node-unisender

bio:
  Hi, I'm Sophia. I am full-stack software engineer with a passion for node.js and web development, currently living in Ukraine.<br/>
  I am passionate about building software that improves the lives of those around me, also really excited about Open Source Software. I have diverse set of skills, ranging from frontend, all the way to backend, databases and infrastructure administration.

experience:
  - date: "January 2020 - present"
    logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMzciIGNsYXNzPSJjc3MtZ2hoZWF3LVN1bVVwTG9nbyBlMTZ2bzhhNjAiIHZpZXdCb3g9IjAgMCA2MyA2MyIgd2lkdGg9IjM3Ij48ZyBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoLz48cGF0aCBkPSJNNTguMi41SDUuMUMyLjcuNS43IDIuNS43IDQuOXY1Mi44YzAgMi40IDIgNC40IDQuNCA0LjRoNTMuMWMyLjQgMCA0LjQtMiA0LjQtNC40VjQuOWMwLTIuNS0yLTQuNC00LjQtNC40ek0zOS41IDQ2LjhjLTUuNCA1LjQtMTQgNS42LTE5LjcuN2wtLjEtLjFjLS4zLS4zLS40LS45IDAtMS4zTDM4LjkgMjdjLjQtLjMuOS0uMyAxLjMgMCA1IDUuOCA0LjggMTQuNC0uNyAxOS44em00LTMwLjVMMjQuMyAzNS40Yy0uNC4zLS45LjMtMS4zIDAtNS01LjctNC44LTE0LjMuNi0xOS43IDUuNC01LjQgMTQtNS42IDE5LjctLjcgMCAwIC4xIDAgLjEuMS41LjMuNS45LjEgMS4yeiIgZmlsbC1ydWxlPSJub256ZXJvIi8+PC9nPjwvc3ZnPg=="
    title: "SumUp"
    link: https://sumup.com/
    description: "SumUp is a leading financial technology company, operating across 32 markets on 3 continents. We empower business owners by enabling them to accept card payments in-store, in-app and online, in a simple, secure and cost-effective way."

  - date: "February 2017 - present"
    logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHYAAABkCAYAAABTucSBAAAACXBIWXMAACxLAAAsSwGlPZapAAAKgElEQVR42u2dS4xbVxmAj90EgdR0RxPxEFXbDVVLkVAXEBawhCzbbdpuSlkU0QrEAqkL1AVRKwQqr0xAZHzvTNI2adWWFXTZqJnQ9EUqkkKmPtfTQJtkQhKpgGbsa/7HeV3Pw2OP7XuO77H0696ZiSL7fv4f5z//+X8h0qwbReYiyXK6T2Qb7j+G6zLIeZBT8PPLcH0a5DGQfSC3iqS5U/S+UnkD/K0Ogvf8u0SKcl4RrBUNd64FstQVRy50xTMfdsVzl7vihatd8fy/u2L+AsL/H8g5kDmQ74F8ScwCVPeVZAi5VgA834pgS9RYvqer7Chpw99WQFbp3yL4o/9i0MevKC2XZ0CeAvm6ONis9QCui0bLAk6yCLZ8LZYIfAPoCJqENZs0+gP8d2+B/Ajk846ZrhPgw+ct4MZiBOs3bAWaIefi2Y8YciKvgRwCudt53myi8dVAX5xFsJ6DdiG3CfL8kgaM2j0P17usicZAK9MMGHIE662s1WRtqq0v/jXIbnr2c+Rv68oX20g6gvUcshuQacCswZfgbw8XtbfpBFcygg1Di11TDdE1LqOOL+PPr4DcroDWje8dCdz44MtYUkGgJVfFMYJ7HeRBR3vrBu62THN86JNNgBi4BHiVlkfHLuP9jJhdrBvTvG2/Gx94SVG0dLQ3ayvf+xpEx3sU3B3MZ2lIsxwftC/B1YoyzRlAv6sAd6icc3zA/iQ7EC4mN9jv7lUZK4Y7/6EwkXMEG2Qma1Uc/afeaPim8rUMNwGznDYj2ICTG6viiIG7twC3kW0Rbnygfi2J1mrudZOKdKPlvj43PlAPgypp4bLPzZxoub61YCo+SL+XQ6nU0TIshc5pqLX+cOOD9Lmaw0bLvM6dUczqogF+Nm2xz41gA42W+dpWGaoHFDeVwJARbOB7vR1VnYHB1G39/W18eOEU2eHGAe8K/dls0FOJzXo55fjgwtn60/u6HEx9p7gEimDD1lo0yUeoBPYiLIFu3jhKjg8tRLg6Sv6lKZCbORvBBp92dBMYibyzEEjNNSPYsKNk8LVcIJfata1bzuqWTsYHF2LasU1HTFytVaRzR83jQwtJazFCZl970ETIWNKKWakINXCtxaL0RF6F5dDnChGyqlqPpjhccwxaS772ByZCplMFibxMRwZt5Xp8aGGZ5bba2ntTzLzp1Ecl8jSdFONquQg2TK3NlXJ+1QZRify9csCrUWMDrXREdszwgDHH8MP94rlLXdoWKlbMRQnJHLPVfUcc1kueRO4BuaK2hKI5DtYct4qZKAWXzTGWYcQIOdR1rc5EPeKCvVMdu+/dtY8PLZwKR+1nE9Gzn/cUdUbhJhrFOtcoIZjjDjU8oW422KpIZypmFz9BTTGwrkab5Ki5AZ3ik3rJg0Xmt/SeybyNNnBxwetqboQbTuEbB8Hftpuz1iR/meCS5gJcC9WeDovi6Sa89rPZo3yCS3cv0cf2qKWcPM0+t6UBd5y0Y4Tsp9auiBeu4fXn4rWFBWL5leN/L2ou1q2m8oApw0AV5yTGitoD7Jh1r01slCvmfZgq+rxiAZSuPX5RnDy1UNNwv/XiWdtFzC6F7qD9viRbpgwVavGzF7t0YAhh+yjVg6o+r8pApfIUsVtpnzSae+8f/ybMvl7iNH5Ms93w8346ZpDIV0EkZazS7Bp1IMNr6ULv47qNCyoHt0PHL1N5HoE+jtxOvX4SNZeWPk+88rYodDHRTab067un8fefBLkR/sNdcN1F1zIlkTfB9VNw/QzBZc3NKxcZ85JnWfz13TNdAPoT5LXwFwv3BGpwmtn9vTRjDaadA49fCBc1l8L+KoKlnPHH6GM772wAV5tnPtmlIDekbTCVSHvMIFX35UlNgb2JzHJVNVaXpQK8zpbg+v5KTcPJXREsgAWo3amAG8EWTTFAy6cCbgRbDJ4U1PDhRrDqwBY1JDlPYKcCbgSbOyUyCwZs8HArD1auSSl2pwJu1NjiJkAv2GDhVh2sORVA5TGPrgs2SLgRbHGjfSOwwcGtMljd4JqWOhmXxmwGNii41dZYt5jtrGjInX3BBgM3RsXF8tOtgA0CbqVNsS4YX7YF41sF6z3cqoI1dWg9RzwGAes13GprrHMoSxVFDArWW7jVBJv3rF9/agoShwHrJdyqgtWDmnCpk6qDz1iMOCxY7+BW18fqVgVviPkzwrS63Q5Yr+BWD+z6zUXQDDeWtg/WG7hVA5uopASnEK+CqHZAqvZrFGC9gFslsG7bPbeBV6qGDaOMCmzpcKulsf1b7o0SbKlwqwLWrUTk1gSJiYTdTuOjBlsa3EqAlbk55LxRW9vZpfGBLQVuFcDa2bO6EfXTpq/Tj59wWtqOEezE4U49WNm/dfxsczJgJwp3usHmhXUrD3t4aNNhD+MGOzG4Uw3W6U98zBnPMuecoTqyOHmwE4E7rWDXDlS6Rq0k+g1UmhTYscOdRrDrj0C7f0sj0CYJdqxwpw3smqGFVxHqb+1gBwiU5rKNhxZOGuzY4Opvboqn62XYYHuh6jGjs4tbHzNaBtixwDUtjbBtQRbyifb1BgNjv4/dff2qD2BHDnddjQ2suUjitDLadJQ3dg9Y8hfsSOHaDnM39vRfDitdqKHycUgs/v6a+lw7zOfsO8bbA7Ajg6s/bIO62WTq294Jog+k29ndaup/Qb5RhNraZBCwh2BHAleDPfwu3p+gJmM8eiYPByoESuxT0fzuVTEDQ33mwtY01Tew24bLHWx0YDFDHeS4PWDub5CUuePnVlTBd+bs2OxY88UNEewI4OrgYn9xgIVncItbbx16n7xbcwJcyZ4CVKxfSuXgCRvfwA4NN5Xu+u5marDh2wCLpLdrLPhTfI+cUTooDv2jVviCppldxk0D2KHgJqp6IDHm+BAPsMg8GWBRiHo7zrz16yZN2LtOTZrDb4r4CnYbmqsfzB3kY/lMS5kDLIq+FAMk3E9lqH8Cud28bzejNKymhgB2YLgmSZFpX3uAg6iC1uYlJBtyMyWFfelHIA87ee4dPGhQWZ7DTbHtl+9gB4F7wphl9c1P5U6qkGcftrLmgY9rQ7yQGpQMlAvPsEbpVyCfVkBr1vRmg0e+oYMdBK5pyWt91a1mgEUypgEWthYpV8ca26ShONuVNRTW03K+MMVK1wCbIGmEUEMCOwjc+3QzbWuS7zYDLBJngMWwptldQunzqUnWVtqZ05eINRQr9H9n6n4NUO1Lm6MHGiLYQeDue+lsL9ziAAs2i2qAxWYDpGRv8KO1sqNAsqnF86m4Z8q9DN8C+SHIZwvRLspvWjbhcPSD8R15CQ1sP7iqUzp9tnue7x1g8f5OOkNKAyyu2AEWqQu5IB1Vad9WPnrVzGrFRh5oZlkz0fS+DfIkzXD92XtuAQADNYUAI4h4pxVsP7jujAMTKSeFARZfpHUu7gJhhgoBocbRGdOMNRrvcVmCv0cTjh3PaJrJBZ2gP0dV+NjzAU39H1q1nooONrkm2sWUZ2tyB8FDBbseXNUG/3H+XEpz3W2upFkrtL7nEav7lR98ncaas4n+j7p/H+Qk9SZM5C9Avg+yD+QLIsX5cWv2hG9QJtfdRiyl18r/AWohxBMMR93zAAAAAElFTkSuQmCC"
    title: "Debitoor"
    link: https://debitoor.com/
    description: "Debitoor is easy-to-use online invoicing and accounting software designed for freelancers and small businesses. We are helping small businesses thrive by creating beautiful and simple tools to run business online: tools to invoice and get paid, keep a financial overview, work with customers and accountants."
    technologies: "node.js, MongoDB, RabbitMQ, AWS, CI/CD, react, webpack, gulp, backbone"

  - date: "May 2015 - January 2017"
    logo: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCABkAGQDASIAAhEBAxEB/8QAHQABAAICAwEBAAAAAAAAAAAAAAUGBAcBAggDCf/EADgQAAEDAwIEAwYDBwUAAAAAAAEAAgMEBREGQRIhMVEHYXETFCJSgZEIFbEWIzIzocHhgoOy0fD/xAAcAQABBQEBAQAAAAAAAAAAAAAABAUGBwgDAQL/xAAyEQABAwIEAwYGAQUAAAAAAAABAAIDBBEFBiExEkFRE2FxgcHwIjJCUpGxoTNistHh/9oADAMBAAIRAxEAPwD9U0RdXvbG0ue4NaOpccALwm2pQuyKNOpLW2TgNfAH5xjjCy4q2CYjgmY7PTB6+iTMq6eQ8LJGk9xC6GN7fmaQvuiIlS5oiIhCIukkrIm8T3Bo7krCkvtFEfilI/23H+yTS1MEH9aQN8SB+19tY53yi6kEWNSXKlrs+wmbIR1bnB+3VZK6xyMlbxxuBHUar5ILTYhERF0XiitS6jotKWia418nBDHyDRzc9x6NaNyV5t1Z4j3nWlY8yTvpKLP7ulhcQAPM7nzU545ajlvWrfyuN590tzQ3hB5GVwBcfoCB9+6plFR9OSyxnzNdRXVsmG0zy2GM2NvqcN79wOgG3PwtXAsKipoG1Uwu92ovyHK3f3+S7UdHnBcMnzVrsNVU26QewmfG35QfhPqOiwrdQ8RHJT0NuwAWjmqmh7ZjhLEbEdE61UzXAsctmaW1eZWNirHcvmJzw/4/T0VzBBGRzC1DZqeSQAEFpHQq6WO8SW7hpqs/uOjZPk/x+notO5RzTJJCyCvvY6Bx5HofQ+m1bYhRNDy6L8K1rFr6+OgiL3uAOCcE4AHc+S6XO6RW2DjcQXEEtbnH1J2A7rU2pNVyXmd0cbz7vnm7p7Q7eg7D6lPeb85U2W4C1p4pjsP9+9BrzAKOhoH1jujRzUxedZz10rmUzzHF09p0c707D+qio6gudxOcXE7k5Kho5FmRSLIFZjdditQaiskLieXIeA5fvrcqaNpY4W8LBZT1POWkEOII6EHorbY9Ruc5lPVuyXHhZMdzsHf9qh08+N1IxSte0tdzaRghWLlnMdThkofE7Tm3kR757hNVTTNlFnBbQRRWmri642tjpHcU0TjFI47kb/UYP1Ra4pahlXAyoj+VwBHmoc9hjcWHcLzZq+J0mub9x83e+y/8uX9ML60FFxkBWTxhsD7NrL8xaw+63JocHAchK0AOH1AB+/ZRdtxgELEeY6OSgxeohmH1uPiCbg+YIKuOCoEtHFIw6Fo/gWP8qVoLRJyLSFYaK0yuLQQMKJpKh0eMBTFHc3xkHBXtDU4ZGR2xITHUulOytVqtBZjLcKWqbWHxc8DG5UfZrj7y3I5NaMucegCXLUMUjHRxu+Ab91oahkwpuG9qNWkad/vqog8TvlsqdrKplkDKWFxbTMGDk8346D0GwVS9k5h6hTepLiHyciCFWZ6zI6rK+Yp31WJyPJuOXQDoO73up3QxFsIaAs5kobusiOfHQqAbV4PVZEdX5pjayyWuhVihqenNSFPU+arEdZ5rJ/M2U8bpHu4WMHE4+SfaOQxuFkhkpyVf9MzVUkVb7vxFgqADjv7NiKwaDtE1o05CKlns6yoc6pnYerHO5hv+lvC36IttYJh0kGG08cziHBouOh3t5Kv6qob2zuEAi+/gs/UWnqLVFqloK+P2kL+YI5OY4dHNOxC0ncNIV2mLs6ic4VIwXROHwukZ3A3xvjp9lv8AUVqPTlJqe3OpKtpGDxRys5Pifs5p2P69DyTTm3KcGYoO0YLTtHwna/8Aad9Ohtp+V3w3En0R7Nx+A7jp3j3qtS0lHO7AMEgPYtKl20DKOH29fMyipx1dIeZ9BuqhqL890hcHUFVWTs5F0UrHuDJmfM3t5jY+WCqrW3GWokL5pXzP+aRxcf6rJM8FNh1Q6GqheZGGxa4hov321I8CL9VPGUb6oB7XjhPMaq9XnW4qnNoraHU9vYcku/imPd3l5KKn1PJxkF/2VTZXhhJysaW4ZcTlJ5cTrZ3FxfbkANAANgBsAPeqdIsOiYOFrVZKu5mRxDuh3Kjpqnh35KJfcg6PrzWFNc+WCU2dk+R3E7dOEdPbQBTJrwHdV9GXEd1VvfuJ2cr6i4ta0kuAAGSSeQCUCnslBp1a23EMaXOcGtAySTgAd1tHwz0FNcH097u0bo6ZhElJSSDBeeoleNu7W+hPPAER4R+FklzFPfb7AWUoxJR0MrcGTcSyA7btafU7BbyWisi5G7LgxXFG67sYeXRzh16Dluddq5xzFmsJpaU67E+g9SuURFoFQFEREIURqfS9Fqy2Poq1nLPFHK3k+J2zmnv+vQrzVrTTFdpC5vpKxuWn4opmj4JW9x/cbfZerFDaq0rQ6vtMlDXMy0845G/xRu2c3/3NVtnDJ8OYoe2hs2oaND9w+13oeXgpJg+Lvw6TgfrGdx07x71Xj6euMbiMrEkryd8Kd1/ouv0VdX0dYzLDl0M7R8Mje4/uNvsqRNNjKytLQyUsroJ2lr2mxB5K7KYx1EYljNwdipJ9w4d1iS1xcTz5KLlqg3dYM9yawElwC6Mp77BOTIOgU6bgGAkuAA5knZb28E/BqS5e76j1HTltLykorfK3+ZuJZAdt2tPqdgo7wE8Cn3H3bU+qKYtp+UtDbZm/zNxLKDtu1p69TsF6XV85NyU1hbiWIt13Y0/5H0HmVWGZMwNYXUVE7XZzh+h6nyCLlEV6qrEREQhEREIRERCFEam0rbNX2x9BdKZtRA7m09HMPzNOxXn3V34WbxHM+SwXOnrISfhhrMxSDy4gCD68l6ZRRjFst4ZjRD6uP4x9Q0P55+d094djNbhmlO/TodR/zysvGsP4Xdf10/BIy3UUecGWWq4hjvhoJW2fDX8LNl0lVw3K/VP7Q3KIh8cbo+Cmid3DOZeR3dy8lvFE34fk7CMPkErWF7htxG9vKwH5CdazNeKVkZiLwxp34Ra/nqfwVwuURTdQ9EREIRERCEREQhEREIRERCEREQhEREIRERCEREQhf//Z"
    title: "Thomas Cook"
    description: "The Thomas Cook Group was the oldest and best known name in leisure travel with a history that started in 1841. I was part of team involved in designing and building multi-language system for tour packages selling, mostly focused on functionality related to tour packages search."
    technologies: "node.js, Angular, grunt, MongoDB, solr"

  - date: "April 2014 - May 2015"
    logo: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDYuOSIgaGVpZ2h0PSI5Ni4xIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZmlsbD0iI2ZmOGEwMCIgZD0iTTExLjkgNDhsNTkuNC0zNC4zVjBMMCA0MS4ydjEzLjdsNzEuMyA0MS4yIDM1LjYtMjAuNlY2MS44TDcxLjMgODIuNCAxMS45IDQ4ek05NSA0MS4yTDU5LjQgNjEuOGwxMS45IDYuOUw5NSA1NC45VjQxLjJ6TTgzLjIgMjAuNkwzNS43IDQ4bDExLjkgNi45IDM1LjctMjAuNlYyMC42eiIvPjwvc3ZnPg=="
    title: "Everad"
    link: https://everad.com/
    description: "Everad is a global direct advertiser and CPA network. I worked on cost-per-action network, cost-per-install network for mobile applications, system for online modifying and deploying websites with versioning."
    technologies: "node.js, postgresql, RabbitMQ, redis, backbone, Angular, cloud9"

  - date: "2012 - April 2014"
    title: Freelance
    description: Various freelance projects including applications for social networks. 
    technologies: "php, mysql, javascript, jQuery"

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sophia-antipenko-531bba82
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 3010618
  telegram: sophia.antipenko
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: https://sophia.antipenko.pp.ua
  # youtube: your_username

# topics:
#   - name: CSS
#     web_url: https://github.com/topics/css
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Web design

#   - name: Sass
#     web_url: https://github.com/topics/sass
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
